AutoMQ/automq-for-rocketmq

broker/src/main/java/com/automq/rocketmq/broker/MetricsExporter.java
store/src/main/java/com/automq/rocketmq/store/metrics/StreamMetricsManager.java

1. Skip initializing StreamMetricsManager when exported disabled

fix(store): skip initializing StreamMetricsManager when exporter disabled

---

broker/src/main/resources/log4j2.xml
metadata-jdbc/src/main/java/com/automq/rocketmq/metadata/HikariCPDataSourceFactory.java
store/src/main/java/com/automq/rocketmq/store/DataStoreFacade.java

fix: set default database connection pool size

---

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java

fix: wal recovery

---

distribution/bin/run-server.sh
distribution/helm/deploy/helm_sample_values.yaml
distribution/helm/templates/broker/_brokerconfig.tpl
distribution/helm/values.yaml

change：
1. sync config files to helm deployments；
2. optimize the parameters of hem value;
3. update the config in helm_sample_values;

feat: sync config files to helm deployments

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/Config.java
s3stream/src/main/java/com/automq/stream/s3/Constants.java
s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java
s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java
s3stream/src/main/java/com/automq/stream/s3/wal/MemoryWriteAheadLog.java
s3stream/src/main/java/com/automq/stream/s3/wal/UnmarshalException.java
s3stream/src/main/java/com/automq/stream/s3/wal/WALHeader.java
s3stream/src/main/java/com/automq/stream/s3/wal/WALMetadata.java
s3stream/src/main/java/com/automq/stream/s3/wal/WriteAheadLog.java
s3stream/src/test/java/com/automq/stream/s3/compact/CompactionManagerTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/BlockWALServiceTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/WALHeaderTest.java

feat(kafka-issues447): WAL record nodeId & epoch metadata

---

s3stream/src/main/java/com/automq/stream/s3/Config.java
s3stream/src/main/java/com/automq/stream/s3/wal/BlockBatch.java
s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java
s3stream/src/main/java/com/automq/stream/s3/wal/SlidingWindowService.java
s3stream/src/main/java/com/automq/stream/s3/wal/WALHeader.java
s3stream/src/main/java/com/automq/stream/s3/wal/WriteAheadLog.java
s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/WriteBench.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java
s3stream/src/test/java/com/automq/stream/s3/wal/BlockWALServiceTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/util/WALChannelTest.java

feat(s3stream/wal): try to flush at a fixed rate

---

s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java
s3stream/src/main/java/com/automq/stream/s3/wal/WALNotInitializedException.java

feat(s3stream): add node id to failover request

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/Config.java
s3stream/src/main/java/com/automq/stream/s3/Constants.java
s3stream/src/main/java/com/automq/stream/s3/failover/Failover.java
s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java
s3stream/src/main/java/com/automq/stream/s3/wal/SlidingWindowService.java
s3stream/src/main/java/com/automq/stream/s3/wal/WALCapacityMismatchException.java
s3stream/src/main/java/com/automq/stream/s3/wal/WALHeader.java
s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/WriteBench.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALUtil.java
s3stream/src/main/java/com/automq/stream/thirdparty/moe/cnkirito/kdio/DirectIOUtils.java
s3stream/src/test/java/com/automq/stream/s3/failover/FailoverTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/BlockWALServiceTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/WALHeaderTest.java

- feat
- "recovery mode" (previously called "read-only") support
- refactor
- remove `windowStartOffset` and `windowNextOffset` in `WALHeader`
- remove `flushWALHeaderScheduler`
- perf
- recover only once, which means there's no recovery on startup
- read `windowMaxLength` rather than the whole WAL during recovery

perf(wal): speed up recovery

---

s3stream/src/main/java/com/automq/stream/s3/DeltaWALUploadTask.java
s3stream/src/main/java/com/automq/stream/s3/ObjectWriter.java
s3stream/src/main/java/com/automq/stream/s3/compact/CompactionUtils.java
s3stream/src/main/java/com/automq/stream/s3/objects/ObjectStreamRange.java
store/src/test/java/com/automq/rocketmq/store/S3ObjectManagerTest.java

close https://github.com/AutoMQ/automq-for-rocketmq/issues/694

feat(issues694): add sub stream size to request

---

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
s3stream/src/main/java/com/automq/stream/utils/biniarysearch/StreamRecordBatchList.java

https://github.com/AutoMQ/automq-for-rocketmq/issues/690

feat(issues690): concurrent read log cache

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/failover/DefaultServerless.java
s3stream/src/main/java/com/automq/stream/s3/failover/Serverless.java

https://github.com/AutoMQ/automq-for-kafka/issues/447%20/opt/automq/scripts/amq-serverless

feat: add default serverless

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java

- fix(issues462): commit wal to closed stream, close https://github.com/AutoMQ/automq-for-kafka/issues/462
- feat(s3stream): 0.5.4

feat(s3stream): 0.5.4

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/Config.java
s3stream/src/main/java/com/automq/stream/s3/cache/BlockCache.java
s3stream/src/main/java/com/automq/stream/s3/cache/DefaultS3BlockCache.java
s3stream/src/main/java/com/automq/stream/s3/cache/ReadAheadAgent.java
s3stream/src/main/java/com/automq/stream/s3/cache/ReadAheadManager.java
s3stream/src/main/java/com/automq/stream/s3/cache/StreamReader.java
s3stream/src/test/java/com/automq/stream/s3/DefaultS3BlockCacheTest.java
s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/BlockCacheTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/ReadAheadManagerTest.java
store/src/main/java/com/automq/rocketmq/store/S3StreamStore.java

- introduce read ahead agent to track sequential read and corresponding read speed
- set default data block size to 1MB

feat(s3stream): dynamically adjust read ahead speed

---

distribution/bin/run-server.sh

fix: revert ZGC option as it causes OOM due to multi-mapping of heap VMA

---

distribution/docker/docker-compose.yaml

fix: escape dollar symbol in docker-compose.xml for linux

---

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
s3stream/src/main/java/com/automq/stream/s3/metrics/operations/S3Operation.java

perf(s3stream/storage): remove the single main write thread

---

s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
s3stream/src/main/java/com/automq/stream/utils/biniarysearch/StreamRecordBatchList.java
s3stream/src/test/java/com/automq/stream/s3/cache/LogCacheTest.java

https://github.com/AutoMQ/automq-for-rocketmq/issues/690

feat(s3stream): optimize cache performance by adding offset index

---

cli/pom.xml

fix: #733 resolve class clashes

---

.github/workflows/release-helm.yml
.github/workflows/release.yml
distribution/helm/charts/automq-for-rocketmq/Chart.yaml

change:
1. release when the tag starts with helm;
2. docker build for helm chart;

chore: release helm chart when the tag starts with helm

---

controller/src/main/java/com/automq/rocketmq/controller/server/store/impl/StreamManager.java

fix: include node-id in close-stream-request during forwarding requests

---

cli/src/main/java/com/automq/rocketmq/cli/ConsoleHelper.java
cli/src/main/java/com/automq/rocketmq/cli/MQAdmin.java
cli/src/main/java/com/automq/rocketmq/cli/broker/DescribeCluster.java
cli/src/main/java/com/automq/rocketmq/cli/broker/TerminateNode.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/ConsumeMessage.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/CreateGroup.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/DeleteGroup.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/DescribeGroup.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/ListGroup.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/ResetConsumeOffset.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/UpdateGroup.java
cli/src/main/java/com/automq/rocketmq/cli/producer/ProduceMessage.java
cli/src/main/java/com/automq/rocketmq/cli/stream/DescribeStream.java
cli/src/main/java/com/automq/rocketmq/cli/topic/CreateTopic.java
cli/src/main/java/com/automq/rocketmq/cli/topic/DeleteTopic.java
cli/src/main/java/com/automq/rocketmq/cli/topic/DescribeTopic.java
cli/src/main/java/com/automq/rocketmq/cli/topic/ListTopic.java
cli/src/main/java/com/automq/rocketmq/cli/topic/UpdateTopic.java

change:
1. refactor cmd line in cli;

refactor: refactor cmd line in cli

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/api/exceptions/FastReadFailFastException.java
s3stream/src/main/java/com/automq/stream/api/exceptions/StreamClientException.java
s3stream/src/main/java/com/automq/stream/s3/S3Stream.java

close https://github.com/AutoMQ/automq-for-kafka/issues/475

fix(kafka_issues475): do not log when fast fail

---

cli/src/main/java/com/automq/rocketmq/cli/consumer/ConsumeMessage.java
cli/src/main/java/com/automq/rocketmq/cli/consumer/CreateGroup.java
cli/src/main/java/com/automq/rocketmq/cli/stream/DescribeStream.java
controller/src/main/java/com/automq/rocketmq/controller/ControllerClient.java
controller/src/main/java/com/automq/rocketmq/controller/client/GrpcControllerClient.java
controller/src/main/java/com/automq/rocketmq/controller/server/store/impl/GroupManager.java
controller/src/main/java/com/automq/rocketmq/controller/server/store/impl/StreamManager.java
controller/src/test/java/com/automq/rocketmq/controller/ControllerServiceImplTest.java
proto/src/main/proto/controller/controller.proto

fix: unify controller error handling while forwarding requests to leader node

---

.github/workflows/nightly-build.yml

change:
1. support nightly build in three different versions: latest, tag version, nightly version;

chore: support nightly build in three different versions

---

s3stream/src/main/java/com/automq/stream/api/Stream.java
s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/cache/BlockCache.java
s3stream/src/main/java/com/automq/stream/s3/cache/DataBlockReadAccumulator.java
s3stream/src/main/java/com/automq/stream/s3/cache/DefaultS3BlockCache.java
s3stream/src/main/java/com/automq/stream/s3/cache/InflightReadThrottle.java
s3stream/src/main/java/com/automq/stream/s3/cache/ReadAheadAgent.java
s3stream/src/main/java/com/automq/stream/s3/cache/StreamReader.java
s3stream/src/main/java/com/automq/stream/s3/metrics/stats/BlockCacheMetricsStats.java
s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
s3stream/src/main/java/com/automq/stream/utils/Utils.java
s3stream/src/test/java/com/automq/stream/s3/DefaultS3BlockCacheTest.java
s3stream/src/test/java/com/automq/stream/s3/ObjectReaderTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/BlockCacheTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/DataBlockReadAccumulatorTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/InflightReadThrottleTest.java
s3stream/src/test/java/com/automq/stream/s3/operator/DefaultS3OperatorTest.java

1. limit inflight memory consumption for read ahead
2. async wait for inflight read ahead task completion instead of blocking wait

feat(s3stream): block cache memory optimization

---

controller/src/main/java/com/automq/rocketmq/controller/server/store/DefaultMetadataStore.java

fixes: https://github.com/AutoMQ/automq-for-rocketmq/issues/787
change:
1. fix non-unique instance id in the node;

fix: fix non-unique instance id in the node

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java
s3stream/src/main/java/com/automq/stream/s3/operator/S3Operator.java

This pull request aims to resolve compatibility issues when running the S3 stream on Aliyun OSS.
Currently, the AWS SDK throws an exception with the message "The request signature we calculated does not match the signature you provided." It appears that Aliyun OSS does not support paths starting with '/'. A similar issue can be referred [here](https://stackoverflow.com/questions/57170720/aws-s3-the-request-signature-we-calculated-does-not-match-the-signature-you-pro). Perhaps Aliyun has not fixed this particular issue.

fix(s3Stream): support aliyun oss

---

broker/src/main/java/com/automq/rocketmq/broker/BrokerController.java
cli/src/main/java/com/automq/rocketmq/cli/MQAdmin.java
cli/src/main/java/com/automq/rocketmq/cli/producer/ProducerClientConnection.java
proto/src/main/proto/proxy/proxy.proto
proxy/src/main/java/com/automq/rocketmq/proxy/grpc/ProxyClient.java
proxy/src/main/java/com/automq/rocketmq/proxy/grpc/ProxyServiceImpl.java
proxy/src/main/java/com/automq/rocketmq/proxy/grpc/client/GrpcProxyClient.java

Output example:
```
┌─────────────────────────┬──────────┬──────────┬─────────────────────┬──────────┐
│        CLIENT ID        │ PROTOCOL │ VERSION  │       ADDRESS       │ LANGUAGE │
├─────────────────────────┼──────────┼──────────┼─────────────────────┼──────────┤
│SSpiritss-MBP.lan@19191#0│ GRPC_V2  │  V5_1_3  │0:0:0:0:0:0:0:1:56520│   RUST   │
└─────────────────────────┴──────────┴──────────┴─────────────────────┴──────────┘
```

feat(cli): add ProducerClientConnection command

---

cli/src/main/java/com/automq/rocketmq/cli/MQAdmin.java
cli/src/main/java/com/automq/rocketmq/cli/topic/ReassignTopic.java
common/src/main/java/com/automq/rocketmq/common/api/DataStore.java
controller/src/main/java/com/automq/rocketmq/controller/server/store/DefaultMetadataStore.java
controller/src/main/java/com/automq/rocketmq/controller/server/tasks/LeaseTask.java
controller/src/test/java/com/automq/rocketmq/controller/server/store/DefaultMetadataStoreTest.java
metadata-jdbc/src/main/java/com/automq/rocketmq/metadata/mapper/StreamMapper.java
metadata-jdbc/src/main/resources/database/mapper/StreamMapper.xml
store/src/main/java/com/automq/rocketmq/store/DataStoreFacade.java

Transfer one queue from node 1 to node 2 in 1s (without updating dirty data to S3).

feat(controller): reassign topic

---

cli/pom.xml
cli/src/main/java/com/automq/rocketmq/cli/producer/ProduceMessage.java
cli/src/main/resources/log4j2.xml
controller/src/main/java/com/automq/rocketmq/controller/server/store/DefaultMetadataStore.java
proxy/src/main/java/com/automq/rocketmq/proxy/service/MessageServiceImpl.java
proxy/src/main/java/com/automq/rocketmq/proxy/service/TopicRouteServiceImpl.java
proxy/src/test/java/com/automq/rocketmq/proxy/service/TopicRouteServiceImplTest.java

Test by reassigning queue 0 from node 2 to node 1 while sending messages at a rate of 500 tps with two producers.
Timeline:
- 15:37:24.500: start to reassign queue 0 from node 2 to node 1
- 15:37:27.488: close queue in node 2
- 15:37:27.901: open queue in node 1
- 15:37:34: all messages are sent successfully after retrying
Server log:
```
docker-broker-2-1  | 2023-12-11 15:37:24.500 INFO  Node[node-id=1] starts to yield topic-id=1 queue-id=0 to node[node-id=2]
docker-broker-2-1  | 2023-12-11 15:37:24.504 INFO  Invoke DataStore to close queue[topic-id=1, queue-id=0]
docker-broker-2-1  | 2023-12-11 15:37:24.505 INFO  [DefaultLogicQueueManager]: Close logic queue: 1 queue: 0
docker-broker-2-1  | 2023-12-11 15:37:27.404 INFO  commitStreamSetObject with StreamSetObject=[broker_id: 1 object_id: …
```

feat(proxy): optimize forward message to another node

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/wal/SlidingWindowService.java
s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java

close https://github.com/AutoMQ/automq-for-kafka/issues/581

fix(kafka_issues581): fix over capacity deadlock

---

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/metrics/operations/S3Operation.java

perf(S3Storage): speed up `forceUpload`

---

s3stream/src/main/java/com/automq/stream/s3/operator/DefaultS3Operator.java

fix(s3stream): fix infinite loop in s3 check

---

pom.xml
s3stream/pom.xml
s3stream/src/main/java/com/automq/stream/utils/biniarysearch/AbstractOrderedCollection.java
s3stream/src/main/java/com/automq/stream/utils/biniarysearch/IndexBlockOrderedBytes.java
s3stream/src/main/java/com/automq/stream/utils/biniarysearch/StreamRecordBatchList.java

feat(s3stream): make AbstractOrderedCollection could be extented by others

---

s3stream/src/main/java/com/automq/stream/s3/wal/SlidingWindowService.java
s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/WriteBench.java

fix(s3stream/wal): fix checks before `scaleOutWindow`

---

.github/workflows/s3-stream-e2e.yml
s3stream/pom.xml

The CI will automatically upgrade the s3stream version in the e2e repo.
Example test report: https://github.com/AutoMQ/automq-for-rocketmq/actions/runs/7396048833

ci(stream): add e2e ci

---

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java
s3stream/src/main/java/com/automq/stream/s3/S3Stream.java

part of https://github.com/AutoMQ/automq-for-kafka/issues/621

perf(s3stream): use read lock rather than write lock in append

---

s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
s3stream/src/main/java/com/automq/stream/s3/ObjectWriter.java
s3stream/src/main/java/com/automq/stream/s3/StreamObjectCompactor.java
s3stream/src/main/java/com/automq/stream/s3/cache/DataBlockRecords.java
s3stream/src/test/java/com/automq/stream/s3/DeltaWALUploadTaskTest.java
s3stream/src/test/java/com/automq/stream/s3/ObjectReaderTest.java
s3stream/src/test/java/com/automq/stream/s3/StreamObjectCompactorTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/DataBlockReadAccumulatorTest.java
s3stream/src/test/java/com/automq/stream/s3/cache/StreamReaderTest.java

https://github.com/AutoMQ/automq-for-kafka/issues/642

feat(kafka_issues642): stream object compact group small data blocks

---

s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
s3stream/src/main/java/com/automq/stream/s3/wal/BlockBatch.java
s3stream/src/main/java/com/automq/stream/utils/FutureUtil.java
s3stream/src/main/java/com/automq/stream/utils/biniarysearch/StreamRecordBatchList.java

part of https://github.com/AutoMQ/automq-for-kafka/issues/650
part of https://github.com/AutoMQ/automq-for-kafka/issues/621

perf(s3stream): use `for` loop rather than `stream` in critical paths

---

s3stream/src/main/java/com/automq/stream/utils/S3Utils.java

Give a more readable output of check message like :
```
[ OK ] Write s3 object
[ OK ] Read s3 object
[ OK ] Delete s3 object
[ OK ] Write S3 object
[ OK ] Upload s3 multipart object
[ OK ] Read s3 multipart object
[ OK ] Delete s3 object
```

chore: optimize S3Utils output

---

s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java
s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/BenchTool.java
s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/RecoveryBench.java
s3stream/src/main/java/com/automq/stream/s3/wal/benchmark/WriteBench.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALCachedChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java
s3stream/src/test/java/com/automq/stream/s3/wal/BlockWALServiceTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannelTest.java
s3stream/src/test/java/com/automq/stream/s3/wal/util/WALChannelTest.java

resolve https://github.com/AutoMQ/automq-for-kafka/issues/573
On AWS EBS gp3 (3000 IOPS, 125 MB/s):
Recover 65536 messages (16 KiB each, 1 GiB in total) cost 92.7s -> 15.3s
Recover 65536 messages (4 KiB each, 256 MiB in total) cost 65.8s -> 2.5s

perf(s3stream): speedup wal recovery

---

s3stream/src/main/java/com/automq/stream/s3/metrics/S3StreamMetricsConstant.java

leave the suffix to OTLP backend implementation

refactor(s3stream): remove _total suffix for counter metrics

---

s3stream/src/main/java/com/automq/stream/api/Stream.java
s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
s3stream/src/main/java/com/automq/stream/s3/StreamObjectCompactor.java
s3stream/src/main/java/com/automq/stream/s3/memory/MemoryMetadataManager.java
s3stream/src/main/java/com/automq/stream/s3/objects/CompactStreamObjectRequest.java
s3stream/src/test/java/com/automq/stream/s3/StreamObjectCompactorTest.java
s3stream/src/test/java/com/automq/stream/s3/objects/ObjectManagerTest.java
store/src/main/java/com/automq/rocketmq/store/S3ObjectManager.java
store/src/test/java/com/automq/rocketmq/store/S3ObjectManagerTest.java
store/src/test/java/com/automq/rocketmq/store/mock/MemoryStreamClient.java

NOTICE: this is a breaking change that modified Stream interface

feat(s3stream): support stream epoch when commit stream object

---

s3stream/src/main/java/com/automq/stream/api/Stream.java
s3stream/src/main/java/com/automq/stream/s3/S3Stream.java
s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
s3stream/src/main/java/com/automq/stream/s3/StreamObjectCompactor.java
s3stream/src/main/java/com/automq/stream/utils/CommandUtils.java
s3stream/src/test/java/com/automq/stream/s3/S3StreamTest.java
s3stream/src/test/java/com/automq/stream/s3/StreamObjectCompactorTest.java

https://github.com/AutoMQ/automq-for-kafka/issues/801

feat(issues801): clean expired stream objects when compact

---

s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
s3stream/src/main/java/com/automq/stream/s3/compact/CompactionManager.java
s3stream/src/main/java/com/automq/stream/s3/compact/CompactionUploader.java
s3stream/src/main/java/com/automq/stream/s3/compact/operator/DataBlockReader.java
s3stream/src/main/java/com/automq/stream/utils/Threads.java
s3stream/src/test/java/com/automq/stream/s3/compact/CompactionManagerTest.java

close https://github.com/AutoMQ/automq-for-kafka/issues/790

fix(s3stream): gracefully shutdown compaction manager

---

s3stream/src/main/java/com/automq/stream/s3/S3StreamClient.java
s3stream/src/main/java/com/automq/stream/s3/StreamObjectCompactor.java

close https://github.com/AutoMQ/automq-for-kafka/issues/871

feat(kafka_issues871): add 1min interval between stream object compaction
