proxy/src/main/java/com/automq/rocketmq/proxy/util/FlatMessageUtil.java, store/src/main/java/com/automq/rocketmq/store/service/StreamOperationLogService.java, store/src/main/java/com/automq/rocketmq/store/util/SerializeUtil.java, store/src/test/java/com/automq/rocketmq/store/util/SerializeUtilTest.java
=> fix(store): ignore corrupt operation when recovering

distribution/bin/run-server.sh
1. fix the distribution of run server;
=> fix: fix the distribution of run server

distribution/docker/build-ci.sh, distribution/helm/clean-ci.sh, distribution/helm/deploy-ci.sh
change:
1. add local init of docker build in ci;
2. satisfies the specified namespace deployment;
User can directly start helm chart without any other dependencies.
=> chore: optimize helm chart deployment

common/src/main/java/com/automq/rocketmq/common/config/S3StreamConfig.java, common/src/main/java/com/automq/rocketmq/common/config/StoreConfig.java, distribution/conf/broker.yaml, store/src/main/java/com/automq/rocketmq/store/MessageStoreBuilder.java
1. add `s3Namespace` configuration item
=> feat(common): add `s3Namespace` configuration item

distribution/bin/run-server.sh
change:
1. fix the java version in run-server;
=> fix: fix the java version in run-server

store/src/main/java/com/automq/rocketmq/store/queue/DefaultLogicQueueStateMachine.java, store/src/test/java/com/automq/rocketmq/store/LogicQueueTest.java, store/src/test/java/com/automq/rocketmq/store/queue/AckCommitterTest.java
1. fix forget to remove old ack-committer when reset consume offset
2. serialize baseOffset of bitmap
=> fix(store): fix forget to remove old ack-committer when reset consume offset

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/failover/Failover.java, s3stream/src/main/java/com/automq/stream/s3/failover/FailoverFactory.java, s3stream/src/main/java/com/automq/stream/s3/failover/FailoverRequest.java, s3stream/src/main/java/com/automq/stream/s3/failover/FailoverResponse.java, s3stream/src/main/java/com/automq/stream/s3/wal/BlockWALService.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALChannel.java
=> feat(kafka-issue447): add delta wal failover

.github/workflows/release.yml
change:
1. trigger relase when tag;
=> chore(ci): trigger relase when tag

distribution/helm/charts/automq-for-rocketmq/Chart.yaml, distribution/helm/charts/automq-for-rocketmq/values.yaml, distribution/kubeblocks/Chart.yaml, distribution/kubeblocks/templates/broker/_brokerconfig.tpl, distribution/kubeblocks/values.yaml
change:
1. update docker image version and repository for helm chart;
2. update helm description in kb;
=> chore: update implementation details of helm chart and kb 

s3stream/src/main/java/com/automq/stream/s3/wal/util/WALBlockDeviceChannel.java, s3stream/src/main/java/com/automq/stream/s3/wal/util/WALFileChannel.java
=> fix(s3stream/wal): fix read file

.github/workflows/nightly-build.yml
change:
1. support for nightly builds in actions;
2. remove redundant dependency tests of distribution build;
=> chore(ci): support for nightly builds in actions

s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/failover/Failover.java
=> fix(issues447): trim the wrong WAL when failover

pom.xml, s3stream/pom.xml, s3stream/src/main/java/com/automq/stream/s3/failover/Failover.java
=> feat(kafka-issues447): skip empty WAL

store/src/main/java/com/automq/rocketmq/store/EmptyFetchResult.java, store/src/main/java/com/automq/rocketmq/store/S3StreamStore.java, store/src/main/java/com/automq/rocketmq/store/api/MessageStateMachine.java, store/src/main/java/com/automq/rocketmq/store/queue/DefaultLogicQueueStateMachine.java, store/src/main/java/com/automq/rocketmq/store/service/StreamOperationLogService.java, store/src/test/java/com/automq/rocketmq/store/MessageStoreTest.java
=> fix: optimize recovery procedure

controller/src/main/java/com/automq/rocketmq/controller/server/store/DefaultMetadataStore.java, controller/src/main/java/com/automq/rocketmq/controller/server/tasks/DataRetentionTask.java
=> fix: simplify data-retention task

controller/src/main/java/com/automq/rocketmq/controller/server/TopicMetricsManager.java, metadata-jdbc/src/main/java/com/automq/rocketmq/metadata/service/DefaultS3MetadataService.java, metadata-jdbc/src/main/java/com/automq/rocketmq/metadata/service/cache/S3ObjectCache.java, metadata-jdbc/src/main/java/com/automq/rocketmq/metadata/service/cache/S3WalObjectCache.java
=> fix: fill WAL base-data-time during commit-of-wal

README.md, docs/CONTRIBUTING.md
=> feat: add contributing guideline

s3stream/pom.xml
=> chore: add maven-source-plugin for s3stream lib

pom.xml, s3stream/pom.xml, s3stream/src/main/java/com/automq/stream/api/ReadOptions.java, s3stream/src/main/java/com/automq/stream/api/Stream.java, s3stream/src/main/java/com/automq/stream/api/exceptions/ErrorCode.java, s3stream/src/main/java/com/automq/stream/api/exceptions/FastReadFailFastException.java, s3stream/src/main/java/com/automq/stream/api/exceptions/StreamClientException.java, s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java, s3stream/src/test/java/com/automq/stream/s3/S3StorageTest.java, s3stream/src/test/java/com/automq/stream/s3/S3StreamTest.java, store/src/test/java/com/automq/rocketmq/store/mock/MemoryStreamClient.java
https://github.com/AutoMQ/automq-for-kafka/issues/471
=> feat(s3stream_kafka471): support fast read option

controller/src/main/java/com/automq/rocketmq/controller/server/store/impl/GroupManager.java, controller/src/main/java/com/automq/rocketmq/controller/server/store/impl/StreamManager.java, metadata/src/main/java/com/automq/rocketmq/metadata/DefaultStoreMetadataService.java
=> fix: handle error when open streams

.github/workflows/release.yml
change:
1. rename release action about docker build;
=> chore: rename release action about docker build

.github/workflows/nightly-build.yml, .github/workflows/pr-e2e-test.yml, distribution/helm/charts/automq-for-rocketmq/templates/broker/_helpers.tpl, distribution/helm/charts/automq-for-rocketmq/templates/broker/service.yaml, distribution/helm/charts/automq-for-rocketmq/templates/broker/statefulset.yaml, distribution/helm/charts/automq-for-rocketmq/values.yaml, distribution/helm/deploy-ci.sh, distribution/helm/deploy/helm_sample_values.yaml
change:
1. update the helm chart to avoid invalid values;
2. update pr-e2e-test and nightly-build action to adapt to the new chart;
3. update deploy-ci to adapt to the new chart;
=> chore: update helm chart to avoid invalid value

pom.xml, s3stream/pom.xml, s3stream/src/main/java/com/automq/stream/s3/failover/DefaultServerless.java, s3stream/src/main/java/com/automq/stream/s3/failover/Failover.java
- jackson ignore unknown field
- delete volume after wal shutdown
=> fix(kafka_issues447): serverless cmd

cli/pom.xml, pom.xml, proxy/pom.xml
=> fix(proxy): remove shaded grpc dependency

pom.xml, s3stream/pom.xml
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/best-practices.html#bestpractice4
=> feat(s3stream): add boringssl dependence

distribution/helm/charts/automq-for-rocketmq/Chart.yaml, distribution/helm/charts/automq-for-rocketmq/values.yaml
change:
1. upgrade chart version to 0.0.4 for new chart release;
2. update tag for user-specified;
3. use appVersion as default;
=> chore: upgrade chart version to 0.0.4

pom.xml, s3stream/pom.xml, s3stream/src/main/java/com/automq/stream/api/ReadOptions.java, s3stream/src/main/java/com/automq/stream/s3/S3Stream.java, s3stream/src/main/java/com/automq/stream/s3/StreamRecordBatchCodec.java, s3stream/src/main/java/com/automq/stream/s3/model/StreamRecordBatch.java, s3stream/src/test/java/com/automq/stream/s3/ObjectWriterTest.java, s3stream/src/test/java/com/automq/stream/s3/StreamObjectCopierTest.java
https://github.com/AutoMQ/automq-for-kafka/issues/500
=> feat(kafka_issues500): add pooledbuf read options

s3stream/src/main/java/com/automq/stream/s3/cache/StreamReader.java, s3stream/src/main/java/com/automq/stream/s3/compact/operator/DataBlockReader.java, s3stream/src/test/java/com/automq/stream/s3/cache/StreamReaderTest.java
Closes https://github.com/AutoMQ/automq-for-kafka/issues/507
=> fix(s3stream): fix potential dangling cf when read not aligned with data block

s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java
close https://github.com/AutoMQ/automq-for-kafka/issues/529
=> fix(kafka_issues529): trim index block

s3stream/src/main/java/com/automq/stream/s3/ObjectReader.java, s3stream/src/main/java/com/automq/stream/s3/StreamRecordBatchCodec.java
part of https://github.com/AutoMQ/automq-for-kafka/issues/543
=> perf(s3stream): not use byte arrays to reduce heap mem alloc when decoding

s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
https://github.com/AutoMQ/automq-for-kafka/issues/563
=> fix(kafka_issues563): check record continuous

pom.xml, s3stream/pom.xml, s3stream/src/main/java/com/automq/stream/s3/S3Storage.java, s3stream/src/main/java/com/automq/stream/s3/cache/LogCache.java
close https://github.com/AutoMQ/automq-for-kafka/issues/562
close https://github.com/AutoMQ/automq-for-kafka/issues/563
=> fix(kafka_issues562): fix duplicated release

s3stream/src/main/java/com/automq/stream/s3/ObjectWriter.java
close https://github.com/AutoMQ/automq-for-kafka/issues/601
=> feat(kafka_issues601): optimize memory usage when upload too much blocks

s3stream/src/main/java/com/automq/stream/s3/StreamObjectCompactor.java, s3stream/src/main/java/com/automq/stream/s3/operator/MultiPartWriter.java
https://github.com/AutoMQ/automq-for-kafka/issues/618
=> feat(s3stream): copy write based on max part size

s3stream/src/main/java/com/automq/stream/s3/trace/aop/S3StreamTraceAspect.java
part of https://github.com/AutoMQ/automq-for-kafka/issues/621
=> perf(s3stream): comment out the trace aspect
